spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:192.168.0.143}
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,refresh,busrefresh
  kafka:
    bootstrap-servers: 192.168.0.143:9092,192.168.0.143:9093,192.168.0.143:9094

  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://192.168.0.143:4318/v1/traces

logging:
  level:
    org.springframework.cloud.gateway: INFO
